# Basic Config
esphome:
  name: athom-zigbee-gateway

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

substitutions:
  devicename: Athom - Zigbee gateway

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

# Enable Web server 
web_server:
  port: 80

# Enable OTA  
ota:
  password: !secret ota_password

# Wifi Setting
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name} Hotspot
    password: !secret wifi_password

# Hotspot    
captive_portal:

# MQTT Brocker conf
#mqtt:
#  broker: !secret mqtt_broker
#  username: !secret mqtt_user
#  password: !secret mqtt_pass
#  reboot_timeout: 30s    

# Enable BLE Tracker and Proxy
esp32_ble_tracker:
  scan_parameters:
    active: true
bluetooth_proxy:
  active: true
 
# Sensors with general information.
sensor:
# Uptime sensor.
  - platform: uptime
    name: ${device_name} Uptime Seconde 
    id: uptime_en_seconde
  
# WiFi Signal sensor.
  - platform: wifi_signal
    name: ${device_name} WiFi Signal
    update_interval: 60s
  
# Text sensors with general information.
text_sensor:
# Expose ESPHome version as sensor.
  - platform: version
    name: ${device_name} ESPHome Version
# UpTime lisible
  - platform: template
    name: ${device_name} Uptime
    lambda: |-
      int seconds = (id(uptime_en_seconde).state);
      int days = seconds / (24 * 3600);
        seconds = seconds % (24 * 3600); 
      int hours = seconds / 3600;
        seconds = seconds % 3600;
      int minutes = seconds /  60;
        seconds = seconds % 60;
      return { (String(days) +" Jours, " + String(hours) +" h, " + String(minutes) +" m, "+ String(seconds) +" s").c_str() };
    icon: mdi:clock-start
    update_interval: 60s
# Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: ${device_name} IP
    ssid:
      name: ${device_name} SSID
    bssid:
      name: ${device_name} BSSID 

button:
  - platform: template
    name: "Zigbee module - Reset"
    id: zigbee_rst
    on_press:
      - switch.turn_on: zigbee_rst_gpio
      - delay: 15ms
      - switch.turn_off: zigbee_rst_gpio

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0

external_components:
  - source: github://oxan/esphome-stream-server

stream_server:
  uart_id: uart_zigbee
  id: ss
  port: 6638

switch:
  - platform: gpio
    pin: 32
    id: zigbee_rst_gpio
    inverted: yes
    restore_mode: ALWAYS_OFF

uart:
  id: uart_zigbee
  baud_rate: 115200
  rx_pin: GPIO14
  tx_pin: GPIO12